# VoxelLoop Essentials Config
# =====================
# Enable AutoUpdate
Auto Update: true

# =====================
# Message Configs
# =====================
JoinMessage: Welcome to the Network of Voxelloopia!
DeathMessage: Ur Ded Get Rekt Kid!
LeaveMessage: Someone just fucked off to shag your mate

# =====================
#
# None of the commands below actually do anything yet lel
#
# =====================

# =====================
# Death Chest Configs
# =====================

# Storage Type ( sqlite | yaml )
StorageType: sqlite

# Require chest in players inventory
RequireChest: true

# Protect chests from other players
ChestProtection: true

# Place sign on death chests
ChestSigns: true

# Allow killers to loot chests
KillerLoot: false

# Automatically remove empty chests on closing
RemoveEmptyChest: true

# List of blocks that can be replaced by a chest
ReplaceableBlocks:
  - AIR
  - LONG_GRASS
  - SNOW
  - VINE
  - WATER_LILY
  - WATER
  - STATIONARY_WATER
  - LAVA
  - STATIONARY_LAVA
# =====================